import { LOOPBACK_HOST } from "./constants.mjs";
import WebSocket from "ws";

function assertPort(port) { if (!Number.isInteger(port) || port < 1024 || port > 65535) throw new Error("CDP port must be between 1024 and 65535"); }
export function isRendererTarget(target) { return target?.type === "page" && typeof target.url === "string" && /^(?:file|app|workbuddy):|(?:renderer|workbuddy)/i.test(target.url) && typeof target.webSocketDebuggerUrl === "string" && target.webSocketDebuggerUrl.startsWith(`ws://${LOOPBACK_HOST}:`); }
export function filterRendererTargets(targets) { if (!Array.isArray(targets)) throw new Error("CDP target list must be an array"); return targets.filter(isRendererTarget); }
export async function discoverTargets(port, { fetchImpl = fetch, timeoutMs = 3000 } = {}) { assertPort(port); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeoutMs); try { const response = await fetchImpl(`http://${LOOPBACK_HOST}:${port}/json/list`, { signal: controller.signal }); if (!response.ok) throw new Error(`CDP discovery HTTP ${response.status}`); return filterRendererTargets(await response.json()); } finally { clearTimeout(timer); } }
export async function waitForTargets(port, { timeoutMs = 5000, pollMs = 150, fetchImpl = fetch } = {}) { const deadline = Date.now() + timeoutMs; let lastError; while (Date.now() < deadline) { try { const targets = await discoverTargets(port, { fetchImpl, timeoutMs: Math.max(100, deadline - Date.now()) }); if (targets.length) return targets; } catch (error) { lastError = error; } await new Promise((resolve) => setTimeout(resolve, pollMs)); } throw new Error(`timed out waiting for WorkBuddy renderer: ${lastError?.message || "no matching target"}`); }

export class CdpSession {
  constructor(url, { WebSocketImpl = WebSocket, timeoutMs = 5000 } = {}) { if (!url?.startsWith(`ws://${LOOPBACK_HOST}:`)) throw new Error("CDP WebSocket must use 127.0.0.1"); this.url = url; this.WebSocketImpl = WebSocketImpl; this.timeoutMs = timeoutMs; this.id = 0; this.pending = new Map(); }
  async connect() { if (this.socket) return this; const socket = new this.WebSocketImpl(this.url); this.socket = socket; try { await new Promise((resolve, reject) => { const timer = setTimeout(() => { try { socket.close(); } catch {} reject(new Error("CDP connection timeout")); }, this.timeoutMs); socket.onopen = () => { clearTimeout(timer); resolve(); }; socket.onerror = () => { clearTimeout(timer); reject(new Error("CDP WebSocket connection failed")); }; }); } catch (error) { if (this.socket === socket) this.socket = null; try { socket.close(); } catch {} throw error; } socket.onmessage = (event) => { try { const msg = JSON.parse(event.data); const pending = this.pending.get(msg.id); if (pending) { this.pending.delete(msg.id); msg.error ? pending.reject(new Error(msg.error.message || "CDP command failed")) : pending.resolve(msg.result); } } catch { /* ignore malformed events */ } }; socket.onclose = () => { this.rejectPending(new Error("CDP connection closed")); if (this.socket === socket) this.socket = null; }; return this; }
  command(method, params = {}) { if (!this.socket) return Promise.reject(new Error("CDP session is not connected")); const id = ++this.id; return new Promise((resolve, reject) => { const timer = setTimeout(() => { this.pending.delete(id); reject(new Error(`CDP ${method} timed out`)); }, this.timeoutMs); this.pending.set(id, { resolve: (value) => { clearTimeout(timer); resolve(value); }, reject: (error) => { clearTimeout(timer); reject(error); } }); try { this.socket.send(JSON.stringify({ id, method, params })); } catch (error) { this.pending.delete(id); clearTimeout(timer); reject(error); } }); }
  async evaluate(expression) { const result = await this.command("Runtime.evaluate", { expression, returnByValue: true, awaitPromise: true }); if (result?.exceptionDetails) throw new Error(result.exceptionDetails.text || "Runtime evaluation failed"); return result?.result?.value; }
  rejectPending(error) { for (const pending of this.pending.values()) pending.reject(error); this.pending.clear(); }
  close() { const socket = this.socket; this.socket = null; this.rejectPending(new Error("CDP connection closed")); try { socket?.close(); } catch {} }
}
