import { mkdir, readdir, readFile, rm, writeFile, stat } from "node:fs/promises";
import { basename, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { getForgeHome } from "./constants.mjs";
import { defaultTheme, validateThemeManifest, themeToCss } from "./theme-schema.mjs";

const builtinRoot = fileURLToPath(new URL("../themes", import.meta.url));
const maxPackageBytes = 32 * 1024 * 1024;

async function ensureDirs() { const home = getForgeHome(); await mkdir(join(home, "themes"), { recursive: true }); await mkdir(join(home, "snapshots"), { recursive: true }); return home; }
async function readThemeDir(dir) { const raw = JSON.parse(await readFile(join(dir, "theme.json"), "utf8")); const manifest = validateThemeManifest(raw); const cssPath = join(dir, "theme.css"); const css = await readFile(cssPath, "utf8").catch(() => themeToCss(manifest)); return { manifest, dir, css }; }
export async function listThemes() { const home = await ensureDirs(); const result = []; for (const root of [builtinRoot, join(home, "themes")]) { for (const entry of await readdir(root, { withFileTypes: true }).catch(() => [])) if (entry.isDirectory()) { try { result.push(await readThemeDir(join(root, entry.name))); } catch { /* skip malformed theme */ } } } return result.filter((x, i, all) => all.findIndex((y) => y.manifest.id === x.manifest.id) === i); }
export async function getTheme(id) { const theme = (await listThemes()).find((x) => x.manifest.id === id); if (!theme) throw new Error(`theme not found: ${id}`); return theme; }
export async function saveTheme(manifest, css = "") { const normalized = validateThemeManifest(manifest); const home = await ensureDirs(); const dir = join(home, "themes", normalized.id); await mkdir(dir, { recursive: true }); await writeFile(join(dir, "theme.json"), JSON.stringify(normalized, null, 2)); await writeFile(join(dir, "theme.css"), css || themeToCss(normalized)); return readThemeDir(dir); }
export async function deleteTheme(id) { const home = await ensureDirs(); const dir = join(home, "themes", id); if (resolve(dir).startsWith(resolve(builtinRoot))) throw new Error("built-in themes cannot be deleted"); await rm(dir, { recursive: true, force: false }); }
export async function createTheme({ image, name }) { const id = name.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || `theme-${Date.now()}`; const ext = basename(image).slice(basename(image).lastIndexOf(".")); if (!/[.](png|jpe?g|webp)$/i.test(ext)) throw new Error("image must be PNG, JPEG, or WebP"); const manifest = defaultTheme({ id, name, assets: { background: `background${ext.toLowerCase()}` } }); const home = await ensureDirs(); const dir = join(home, "themes", id); await mkdir(dir, { recursive: true }); await writeFile(join(dir, "theme.json"), JSON.stringify(manifest, null, 2)); await writeFile(join(dir, "theme.css"), themeToCss(manifest, `background${ext.toLowerCase()}`)); const bytes = await readFile(image); if (bytes.byteLength > maxPackageBytes) throw new Error("image is too large"); await writeFile(join(dir, `background${ext.toLowerCase()}`), bytes); return readThemeDir(dir); }

function crc32(buf) { let crc = 0xffffffff; for (const byte of buf) { crc ^= byte; for (let i = 0; i < 8; i++) crc = (crc >>> 1) ^ (0xedb88320 & -(crc & 1)); } return (crc ^ 0xffffffff) >>> 0; }
function zip(entries) { const chunks = [], central = []; let offset = 0; for (const [name, data] of entries) { const n = Buffer.from(name), d = Buffer.isBuffer(data) ? data : Buffer.from(data); const h = Buffer.alloc(30 + n.length); h.writeUInt32LE(0x04034b50, 0); h.writeUInt16LE(20, 4); h.writeUInt16LE(0, 6); h.writeUInt16LE(0, 8); h.writeUInt32LE(crc32(d), 14); h.writeUInt32LE(d.length, 18); h.writeUInt32LE(d.length, 22); h.writeUInt16LE(n.length, 26); n.copy(h, 30); chunks.push(h, d); const c = Buffer.alloc(46 + n.length); c.writeUInt32LE(0x02014b50, 0); c.writeUInt16LE(20, 4); c.writeUInt16LE(20, 6); c.writeUInt32LE(crc32(d), 16); c.writeUInt32LE(d.length, 20); c.writeUInt32LE(d.length, 24); c.writeUInt16LE(n.length, 28); c.writeUInt32LE(offset, 42); n.copy(c, 46); central.push(c); offset += h.length + d.length; } const directory = Buffer.concat(central); const end = Buffer.alloc(22); end.writeUInt32LE(0x06054b50, 0); end.writeUInt16LE(entries.length, 8); end.writeUInt16LE(entries.length, 10); end.writeUInt32LE(directory.length, 12); end.writeUInt32LE(offset, 16); return Buffer.concat([...chunks, directory, end]); }
function unzip(buffer) { const out = new Map(); let p = 0; while (p + 4 <= buffer.length && buffer.readUInt32LE(p) === 0x04034b50) { const nameLen = buffer.readUInt16LE(p + 26), extraLen = buffer.readUInt16LE(p + 28), size = buffer.readUInt32LE(p + 22); const name = buffer.toString("utf8", p + 30, p + 30 + nameLen); if (name.includes("..") || name.startsWith("/") || name.startsWith("\\")) throw new Error("theme package contains unsafe path"); const start = p + 30 + nameLen + extraLen; out.set(name, buffer.subarray(start, start + size)); p = start + size; } if (!out.has("theme.json")) throw new Error("theme package missing theme.json"); return out; }
export async function exportTheme(id, outFile) { const theme = await getTheme(id); const entries = [["theme.json", JSON.stringify(theme.manifest, null, 2)], ["theme.css", theme.css], ["LICENSE", theme.manifest.license || "CC0-1.0"]]; for (const asset of Object.values(theme.manifest.assets)) { try { entries.push([`assets/${basename(asset)}`, await readFile(join(theme.dir, asset))]); } catch { /* optional asset */ } } await writeFile(outFile, zip(entries)); return outFile; }
export async function importTheme(file) { const bytes = await readFile(file); if (bytes.byteLength > maxPackageBytes) throw new Error("theme package exceeds 32 MiB"); const entries = unzip(bytes); const manifest = validateThemeManifest(JSON.parse(entries.get("theme.json").toString("utf8"))); const home = await ensureDirs(); const dir = join(home, "themes", manifest.id); await mkdir(dir, { recursive: true }); await writeFile(join(dir, "theme.json"), JSON.stringify(manifest, null, 2)); await writeFile(join(dir, "theme.css"), entries.get("theme.css") || themeToCss(manifest)); for (const [name, data] of entries) if (name.startsWith("assets/") && name.split("/").length === 2) await writeFile(join(dir, basename(name)), data); return readThemeDir(dir); }
export { maxPackageBytes };
